### ISSUE TITLE
error when installing xlwings package

### ISSUE THREAD

**Issue by tomnewg** [ideonate/jupyter-containds#11]
Hi Dan,

first of all thank you so much for containDS. I am currently experimenting with it. The installation went smoothly and I am now installing all the packages I need to run a specific jupyter notebook. I managed to install all required packages apart from xlwings. I think xlwings can't find the Excel installation on my computer through containDS. I understand that it doesn't work on the server as Excel is not installed there. But it should work on my computer with containDS. Is there any way to get xlwings work within containDS? Many thanks for your help.

Best,
Tom

This is the error message I get:

> jovyan@19c2f8845a47:~$ pip install xlwings
Collecting xlwings
  Using cached xlwings-0.23.0.tar.gz (769 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7zo2gwgk/xlwings/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7zo2gwgk/xlwings/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-7zo2gwgk/xlwings/pip-egg-info
         cwd: /tmp/pip-install-7zo2gwgk/xlwings/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7zo2gwgk/xlwings/setup.py", line 32, in <module>
        raise OSError("xlwings requires an installation of Excel and therefore only works on Windows and macOS. To enable the installation on Linux nevertheless, do: export INSTALL_ON_LINUX=1; pip install xlwings")
    OSError: xlwings requires an installation of Excel and therefore only works on Windows and macOS. To enable the installation on Linux nevertheless, do: export INSTALL_ON_LINUX=1; pip install xlwings
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by tomnewg** [comment]
I understand now that the container is completely separated from the local machine. And linux is run within the container. Is there any change to change settings that would enable the container to see the local Excel installation and therefore xlwings can be installed?

Many thanks

Tom

**Comment by danlester** [comment]
Accessing the host's Excel installation could be possible from the container depending on how xlwings connects to Excel. If it is through a port then it could be possible. (I'm not sure)

But to be honest, I'm not convinced there is merit in using ContainDS Desktop in this situation anyway. The advantage in having your code within a container is lost if the user also needs dependencies outside the container.

It could be interesting to hear more about what you are trying to achieve in case anyone has any ideas?

**Comment by danlester** [comment]
Oh by the way, this repo is for something unrelated to ContainDS Desktop! But no problem.
