### ISSUE TITLE
extension doesn't support jupyter lab version 3.0

### ISSUE THREAD

**Issue by barperez111** [ideonate/jupyter-containds#16]
Hi!
It seems this extension might be very helpful but doesn't work with lab version 3.0.
is it possible to fix this?

thanx a lot!

**Comment by danlester** [comment]
Thank you for the issue. Frederic is already working on this!

**Comment by fcollonval** [comment]
This is fixed in version 0.2.2

**Comment by danlester** [comment]
Thanks for your hard work Frédéric!

I haven't had a chance to test against JupyterLab 3.0 but I'll close this issue. If anyone tries it and has any problems (or it works!) please let us know.

I should be getting to use it myself in the next few days anyway.

**Comment by fcollonval** [comment]
I can confirm it works - we migrated to JupyterLab 3 last week :wink:
